version: '3.9'

services:

  db:
    restart: always
    image: redis
    ports:
      - 6379:6379
    networks:
      - project-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.hostname
    

  api:
    restart: always
    image: kauahensilva/my_api:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - project-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.hostname

networks:
  project-network:
    driver: overlay
