version: '3.9'

services:

  db:
    restart: always
    image: redis
    ports:
      - 6379:6379
    networks:
      - project-network

  api:
    restart: always
    image: my_api:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - project-network

networks:
  project-network:
    driver: overlay
